dbInfo:
    'database': 'RGI_db'
    'user': 'root'
    'password': 'pass'
    'host' : '127.0.0.1'
    'raise_on_warnings' : True
tables:
    table1:
        name : "user"
        clomns :
            id : "varchar"
